import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  TuiAlertModule,
  TuiButtonModule,
  TuiDataListModule,
  TuiDialogModule,
  TuiFormatNumberPipeModule,
  TuiHintModule,
  TuiHostedDropdownModule,
  TuiModeModule,
  TuiNotificationModule,
  TuiRootModule,
  TuiScrollbarModule,
  TuiSvgModule,
} from '@taiga-ui/core';
import { TuiSidebarModule } from '@taiga-ui/addon-mobile';
import { TuiActiveZoneModule, TuiLetModule } from '@taiga-ui/cdk';
import {
  TuiAvatarModule,
  TuiBadgeModule,
  TuiInputDateModule,
  TuiInputDateRangeModule,
  TuiInputFilesModule,
  TuiInputInlineModule,
  TuiInputNumberModule,
  TuiTabsModule,
  TuiTextAreaModule,
} from '@taiga-ui/kit';
import { TuiTableModule } from '@taiga-ui/addon-table';
import { TuiCurrencyPipeModule } from '@taiga-ui/addon-commerce';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    TuiActiveZoneModule,
    TuiAlertModule,
    TuiAvatarModule,
    TuiBadgeModule,
    TuiButtonModule,
    TuiCurrencyPipeModule,
    TuiDialogModule,
    TuiFormatNumberPipeModule,
    TuiHintModule,
    TuiHostedDropdownModule,
    TuiInputDateModule,
    TuiInputDateRangeModule,
    TuiInputFilesModule,
    TuiInputInlineModule,
    TuiInputNumberModule,
    TuiLetModule,
    TuiModeModule,
    TuiNotificationModule,
    TuiRootModule,
    TuiScrollbarModule,
    TuiSidebarModule,
    TuiSvgModule,
    TuiTableModule,
    TuiTabsModule,
    TuiTextAreaModule,
    TuiDataListModule,
  ],
  exports: [
    TuiActiveZoneModule,
    TuiAlertModule,
    TuiAvatarModule,
    TuiBadgeModule,
    TuiButtonModule,
    TuiCurrencyPipeModule,
    TuiDialogModule,
    TuiFormatNumberPipeModule,
    TuiHintModule,
    TuiHostedDropdownModule,
    TuiInputDateModule,
    TuiInputDateRangeModule,
    TuiInputFilesModule,
    TuiInputInlineModule,
    TuiInputNumberModule,
    TuiLetModule,
    TuiModeModule,
    TuiNotificationModule,
    TuiRootModule,
    TuiScrollbarModule,
    TuiSidebarModule,
    TuiSvgModule,
    TuiTableModule,
    TuiTabsModule,
    TuiTextAreaModule,
    TuiDataListModule,
  ],
})
export class TaigaSharedModule {}
