import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  TuiAlertModule,
  TuiButtonModule,
  TuiDataListModule,
  TuiDialogModule,
  TuiDropdownModule,
  TuiFormatNumberPipeModule,
  TuiHintModule,
  TuiHostedDropdownModule,
  TuiLoaderModule,
  TuiModeModule,
  TuiNotificationModule,
  TuiRootModule,
  TuiScrollbarModule,
  TuiSvgModule,
  TuiTextfieldControllerModule,
} from '@taiga-ui/core';
import { TuiSidebarModule } from '@taiga-ui/addon-mobile';
import { TuiActiveZoneModule, TuiLetModule } from '@taiga-ui/cdk';
import {
  TuiAvatarModule,
  TuiBadgedContentModule,
  TuiBadgeModule,
  TuiCheckboxLabeledModule,
  TuiCheckboxModule,
  TuiDataListWrapperModule,
  TuiInputCountModule,
  TuiInputDateModule,
  TuiInputDateRangeModule,
  TuiInputFilesModule,
  TuiInputInlineModule,
  TuiInputModule,
  TuiInputNumberModule,
  TuiSelectModule,
  TuiTabsModule,
  TuiTextAreaModule,
} from '@taiga-ui/kit';
import { TuiReorderModule, TuiTableModule } from '@taiga-ui/addon-table';
import { TuiCurrencyPipeModule } from '@taiga-ui/addon-commerce';
import { TuiEditorModule } from '@taiga-ui/addon-editor';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    TuiActiveZoneModule,
    TuiAlertModule,
    TuiAvatarModule,
    TuiBadgedContentModule,
    TuiBadgeModule,
    TuiButtonModule,
    TuiCheckboxLabeledModule,
    TuiCheckboxModule,
    TuiCurrencyPipeModule,
    TuiDataListModule,
    TuiDataListWrapperModule,
    TuiDialogModule,
    TuiDropdownModule,
    TuiEditorModule,
    TuiFormatNumberPipeModule,
    TuiHintModule,
    TuiHostedDropdownModule,
    TuiInputCountModule,
    TuiInputDateModule,
    TuiInputDateRangeModule,
    TuiInputFilesModule,
    TuiInputInlineModule,
    TuiInputModule,
    TuiInputNumberModule,
    TuiLetModule,
    TuiLoaderModule,
    TuiModeModule,
    TuiNotificationModule,
    TuiReorderModule,
    TuiRootModule,
    TuiScrollbarModule,
    TuiSelectModule,
    TuiSidebarModule,
    TuiSvgModule,
    TuiTableModule,
    TuiTabsModule,
    TuiTextAreaModule,
    TuiTextfieldControllerModule,
  ],
  exports: [
    TuiActiveZoneModule,
    TuiAlertModule,
    TuiAvatarModule,
    TuiBadgedContentModule,
    TuiBadgeModule,
    TuiButtonModule,
    TuiCheckboxLabeledModule,
    TuiCheckboxModule,
    TuiCurrencyPipeModule,
    TuiDataListModule,
    TuiDataListWrapperModule,
    TuiDialogModule,
    TuiDropdownModule,
    TuiEditorModule,
    TuiFormatNumberPipeModule,
    TuiHintModule,
    TuiHostedDropdownModule,
    TuiInputCountModule,
    TuiInputDateModule,
    TuiInputDateRangeModule,
    TuiInputFilesModule,
    TuiInputInlineModule,
    TuiInputModule,
    TuiInputNumberModule,
    TuiLetModule,
    TuiLoaderModule,
    TuiModeModule,
    TuiNotificationModule,
    TuiReorderModule,
    TuiRootModule,
    TuiScrollbarModule,
    TuiSelectModule,
    TuiSidebarModule,
    TuiSvgModule,
    TuiTableModule,
    TuiTabsModule,
    TuiTextAreaModule,
    TuiTextfieldControllerModule,
  ],
})
export class TaigaSharedModule {}
